# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
