# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20160730_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('created_on',)},
        ),
        migrations.AddField(
            model_name='posts',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
