# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20160730_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(max_length=1500),
        ),
    ]
